name: Build Bazzite Use just

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install just
        run: |
          apt install -y pipx
          pipx install rust-just
          pipx ensurepath
      - name: Build ISO
        run: |
          cd just_scripts/
          ./build-iso.sh
      - name: Collect ISO
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: '**/*.iso'
