name: Build Bazzite Use just

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install just
        run: |
          sudo apt install -y pipx
          pipx install rust-just
          pipx ensurepath
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert username to lowercase
        run: echo "USERNAME=${GITHUB_ACTOR,,}" >> $GITHUB_ENV
      - name: Build image
        run: |
          just build deck
          docker tag localhost/bazzite-deck-build:40-main ghcr.io/${{ env.USERNAME }}/bazzite-deck-build:40-main
          docker images --all
          docker push ghcr.io/${{ env.USERNAME }}/bazzite-deck-build:40-main
