name: Build Bazzite Use just

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install just
        run: |
          sudo apt install -y pipx
          pipx install rust-just
          pipx ensurepath
      - name: Build image
        run: |
          just build deck
          docker images --all
          docker tag localhost/bazzite-deck-build:40-main ghcr.io/akazarenn/bazzite-deck-build:40-main
          docker images --all
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: Wandalen/wretry.action@v3.5.0
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: bazzite-deck-build
            tags: 40-main
            registry: ghcr.io/akazarenn
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
