name: Build Bazzite Use just

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install just
        run: |
          sudo apt install -y pipx
          pipx install rust-just
          pipx ensurepath
      - name: Build image
        run: |
          just build deck
          docker tag localhost/bazzite-deck-build:40-main ghcr.io/${{ github.actor }}/bazzite-deck-build:40-main
          docker images --all
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/bazzite-deck-build:40-main
